import type { Project } from "@shared/schema";

export const projects: Project[] = [
  {
    id: 1,
    title: "AI Code Review Dashboard",
    subtitle: "Full-Stack React + Node.js + AI",
    description:
      "A production-grade code review platform that leverages AI to analyze pull requests, suggest improvements, detect bugs, and enforce coding standards. Features real-time collaboration, inline comments, and automated quality scoring with a beautiful dashboard interface.",
    techStack: ["React", "TypeScript", "Node.js", "Express", "OpenAI API", "WebSocket", "TailwindCSS"],
    category: "fullstack",
    categoryLabel: "Full-Stack",
    features: [
      "AI-powered code analysis with contextual suggestions",
      "Real-time collaborative review with WebSocket",
      "Code quality scoring dashboard with charts",
      "Multi-language syntax highlighting",
      "Git diff viewer with inline annotations",
      "Automated PR review workflow",
    ],
    githubStructure: [
      "src/client/ - React frontend with dashboard components",
      "src/server/ - Express API with AI integration",
      "src/shared/ - Shared types and utilities",
      "README.md - Setup guide and API documentation",
    ],
    difficulty: "advanced",
    instantRun: false,
    icon: "Brain",
    gradient: "from-violet-500 to-purple-600",
  },
  {
    id: 2,
    title: "Banking Payment Flow Simulator",
    subtitle: "Backend Microservices Architecture",
    description:
      "A comprehensive payment processing simulator built with microservices patterns. Simulates real banking workflows including payment initiation, validation, fraud detection, settlement, and reconciliation — reflecting modern core banking modernization patterns used at Danske Bank.",
    techStack: ["Node.js", "Express", "TypeScript", "PostgreSQL", "Redis", "Docker", "Swagger"],
    category: "backend",
    categoryLabel: "Backend",
    features: [
      "Payment initiation and validation pipeline",
      "Fraud detection rules engine",
      "Transaction settlement & reconciliation",
      "Idempotency and retry mechanisms",
      "Comprehensive Swagger API documentation",
      "Event-driven architecture with message queues",
    ],
    githubStructure: [
      "services/payment-gateway/ - Payment initiation service",
      "services/fraud-detection/ - Rule-based fraud engine",
      "services/settlement/ - Settlement processing",
      "shared/types/ - Shared DTOs and interfaces",
      "docker-compose.yml - Multi-service orchestration",
    ],
    difficulty: "advanced",
    instantRun: false,
    icon: "Landmark",
    gradient: "from-emerald-500 to-teal-600",
  },
  {
    id: 3,
    title: "Interactive REST API Playground",
    subtitle: "Single HTML File — Instant Run",
    description:
      "A sleek, self-contained API testing tool in a single HTML file. Features a beautiful UI for constructing HTTP requests, viewing formatted responses, managing request history, and saving collections. Works entirely in the browser — no server needed. Just open the file!",
    techStack: ["HTML5", "CSS3", "Vanilla JavaScript", "Fetch API"],
    category: "html-instant",
    categoryLabel: "HTML Instant Run",
    features: [
      "GET, POST, PUT, PATCH, DELETE request builder",
      "JSON syntax highlighting with formatting",
      "Request history with local storage persistence",
      "Custom headers and auth token management",
      "Response time measurement and status codes",
      "Dark/light mode toggle",
    ],
    githubStructure: [
      "index.html - Complete self-contained application",
      "README.md - Usage guide and screenshots",
    ],
    difficulty: "beginner",
    instantRun: true,
    icon: "Globe",
    gradient: "from-blue-500 to-cyan-600",
  },
  {
    id: 4,
    title: "Microservices Health Monitor",
    subtitle: "Full-Stack Real-time Dashboard",
    description:
      "A real-time microservices monitoring dashboard that tracks health, latency, error rates, and resource utilization across distributed services. Features beautiful animated charts, alerting rules, and service dependency mapping — inspired by enterprise monitoring at scale.",
    techStack: ["React", "TypeScript", "Node.js", "WebSocket", "Recharts", "TailwindCSS"],
    category: "fullstack",
    categoryLabel: "Full-Stack",
    features: [
      "Real-time service health indicators",
      "Latency and throughput charts with historical data",
      "Service dependency topology map",
      "Configurable alerting thresholds",
      "Error rate tracking and anomaly detection",
      "Auto-refreshing dashboard with WebSocket",
    ],
    githubStructure: [
      "client/ - React dashboard with real-time charts",
      "server/ - Express API with WebSocket server",
      "mock-services/ - Simulated microservices",
      "README.md - Architecture and setup guide",
    ],
    difficulty: "intermediate",
    instantRun: false,
    icon: "Activity",
    gradient: "from-orange-500 to-red-500",
  },
  {
    id: 5,
    title: "GenAI Content Automation Pipeline",
    subtitle: "AI Workflow Orchestration",
    description:
      "An intelligent content generation pipeline that orchestrates multiple AI agents to research topics, generate drafts, edit content, and publish — all through a visual workflow builder. Demonstrates advanced GenAI patterns including prompt chaining, agent coordination, and quality gates.",
    techStack: ["React", "TypeScript", "Node.js", "OpenAI API", "LangChain", "TailwindCSS"],
    category: "ai-genai",
    categoryLabel: "AI / GenAI",
    features: [
      "Visual drag-and-drop workflow builder",
      "Multi-agent orchestration (researcher, writer, editor)",
      "Prompt template management system",
      "Content quality scoring and iteration",
      "Batch processing with progress tracking",
      "Export to Markdown, HTML, and PDF",
    ],
    githubStructure: [
      "client/ - React workflow builder UI",
      "server/ - Express orchestration engine",
      "agents/ - AI agent implementations",
      "templates/ - Prompt template library",
      "README.md - Architecture and AI patterns",
    ],
    difficulty: "advanced",
    instantRun: false,
    icon: "Sparkles",
    gradient: "from-pink-500 to-rose-600",
  },
  {
    id: 6,
    title: "Real-time Analytics Dashboard",
    subtitle: "Single HTML File — Instant Run",
    description:
      "A stunning real-time analytics dashboard in a single HTML file. Features animated charts, KPI cards, data tables, and interactive filters — all with mock data that simulates live updates. Perfect for demonstrating frontend data visualization skills. Just open and go!",
    techStack: ["HTML5", "CSS3", "JavaScript", "Chart.js", "CSS Animations"],
    category: "html-instant",
    categoryLabel: "HTML Instant Run",
    features: [
      "Animated KPI cards with trend indicators",
      "Multiple chart types (line, bar, doughnut, radar)",
      "Interactive data filtering and date ranges",
      "Responsive grid layout for any screen size",
      "Simulated real-time data updates",
      "Export dashboard as screenshot",
    ],
    githubStructure: [
      "index.html - Complete analytics dashboard",
      "README.md - Customization guide",
    ],
    difficulty: "beginner",
    instantRun: true,
    icon: "BarChart3",
    gradient: "from-indigo-500 to-blue-600",
  },
  {
    id: 7,
    title: "GitHub Copilot Workflow Bot",
    subtitle: "AI-Powered Developer Automation",
    description:
      "An intelligent GitHub bot that automates PR reviews, generates documentation, suggests test cases, and enforces coding standards using AI. Inspired by the winning project at the Danske Bank GitHub Copilot Hackathon — demonstrates practical AI-assisted developer workflows.",
    techStack: ["Node.js", "TypeScript", "GitHub API", "OpenAI API", "Webhooks", "Express"],
    category: "ai-genai",
    categoryLabel: "AI / GenAI",
    features: [
      "Automated PR code review with AI suggestions",
      "Auto-generated documentation from code",
      "Test case generation for new functions",
      "Code style enforcement and linting",
      "Webhook-based event handling",
      "Configurable review rules and thresholds",
    ],
    githubStructure: [
      "src/ - Bot core logic and AI integration",
      "webhooks/ - GitHub webhook handlers",
      "templates/ - Review and doc templates",
      "config/ - Bot configuration and rules",
      "README.md - Setup and deployment guide",
    ],
    difficulty: "intermediate",
    instantRun: false,
    icon: "Bot",
    gradient: "from-amber-500 to-orange-600",
  },
  {
    id: 8,
    title: "Smart Error Monitoring System",
    subtitle: "Full-Stack Error Tracking Platform",
    description:
      "A production-grade error monitoring and alerting system. Captures, categorizes, and visualizes application errors with stack traces, user context, and frequency analysis. Features intelligent error grouping, trend detection, and notification workflows — reducing exceptions by design.",
    techStack: ["React", "TypeScript", "Node.js", "Express", "PostgreSQL", "TailwindCSS"],
    category: "fullstack",
    categoryLabel: "Full-Stack",
    features: [
      "Intelligent error grouping and deduplication",
      "Stack trace visualization with source maps",
      "Error frequency trends and anomaly detection",
      "User impact analysis dashboard",
      "Email/webhook notification workflows",
      "SDK for easy integration into any app",
    ],
    githubStructure: [
      "dashboard/ - React error monitoring UI",
      "server/ - Express ingestion and API server",
      "sdk/ - JavaScript error capture SDK",
      "database/ - PostgreSQL schema and migrations",
      "README.md - Integration guide",
    ],
    difficulty: "advanced",
    instantRun: false,
    icon: "ShieldAlert",
    gradient: "from-red-500 to-pink-600",
  },
  {
    id: 9,
    title: "AI Chat Interface",
    subtitle: "Single HTML File — Instant Run",
    description:
      "A beautiful, production-quality AI chat interface in a single HTML file. Features streaming message animations, markdown rendering, code syntax highlighting, conversation management, and a modern glass-morphism design. Demonstrates advanced CSS and frontend polish.",
    techStack: ["HTML5", "CSS3", "JavaScript", "Marked.js", "Highlight.js", "CSS Glass Effects"],
    category: "html-instant",
    categoryLabel: "HTML Instant Run",
    features: [
      "Streaming text animation with typewriter effect",
      "Markdown rendering with code highlighting",
      "Conversation management (new, delete, rename)",
      "Message reactions and copy functionality",
      "Responsive mobile-first design",
      "Glass-morphism UI with smooth transitions",
    ],
    githubStructure: [
      "index.html - Complete chat application",
      "README.md - Customization and API integration guide",
    ],
    difficulty: "beginner",
    instantRun: true,
    icon: "MessageSquare",
    gradient: "from-teal-500 to-emerald-600",
  },
  {
    id: 10,
    title: "CI/CD Pipeline Visualizer",
    subtitle: "Frontend React Application",
    description:
      "A visual pipeline builder and executor dashboard for CI/CD workflows. Drag and drop pipeline stages, configure jobs, view execution logs, and track deployment history — all with beautiful animations and real-time progress indicators. Showcases advanced React patterns and state management.",
    techStack: ["React", "TypeScript", "Framer Motion", "TailwindCSS", "Zustand"],
    category: "frontend",
    categoryLabel: "Frontend",
    features: [
      "Drag-and-drop pipeline stage builder",
      "Real-time execution progress visualization",
      "Job configuration with environment variables",
      "Execution log streaming with ANSI colors",
      "Deployment history timeline",
      "Pipeline YAML export and import",
    ],
    githubStructure: [
      "src/components/ - React pipeline components",
      "src/store/ - Zustand state management",
      "src/utils/ - Pipeline parsing and execution",
      "src/types/ - TypeScript interfaces",
      "README.md - Architecture and patterns guide",
    ],
    difficulty: "intermediate",
    instantRun: false,
    icon: "GitBranch",
    gradient: "from-cyan-500 to-blue-600",
  },
];
