import type { Project } from "@shared/schema";

export const projects: Project[] = [
  {
    id: 1,
    title: "AI Code Review Dashboard",
    subtitle: "Full-Stack React + Node.js + AI",
    description:
      "A production-grade code review platform that leverages AI to analyze pull requests, suggest improvements, detect bugs, and enforce coding standards. Features real-time collaboration, inline comments, and automated quality scoring with a beautiful dashboard interface.",
    techStack: ["React", "TypeScript", "Node.js", "Express", "OpenAI API", "WebSocket", "TailwindCSS"],
    category: "fullstack",
    categoryLabel: "Full-Stack",
    features: [
      "AI-powered code analysis with contextual suggestions",
      "Real-time collaborative review with WebSocket",
      "Code quality scoring dashboard with charts",
      "Multi-language syntax highlighting",
      "Git diff viewer with inline annotations",
      "Automated PR review workflow",
    ],
    githubStructure: [
      "src/client/ - React frontend with dashboard components",
      "src/server/ - Express API with AI integration",
      "src/shared/ - Shared types and utilities",
      "README.md - Setup guide and API documentation",
    ],
    difficulty: "advanced",
    instantRun: false,
    icon: "Brain",
    gradient: "from-violet-500 to-purple-600",
  },
  {
    id: 2,
    title: "Banking Payment Flow Simulator",
    subtitle: "Backend Microservices Architecture",
    description:
      "A comprehensive payment processing simulator built with microservices patterns. Simulates real banking workflows including payment initiation, validation, fraud detection, settlement, and reconciliation.",
    techStack: ["Node.js", "Express", "TypeScript", "PostgreSQL", "Redis", "Docker", "Swagger"],
    category: "backend",
    categoryLabel: "Backend",
    features: [
      "Payment initiation and validation pipeline",
      "Fraud detection rules engine",
      "Transaction settlement & reconciliation",
      "Idempotency and retry mechanisms",
      "Comprehensive Swagger API documentation",
      "Event-driven architecture with message queues",
    ],
    githubStructure: [
      "services/payment-gateway/ - Payment initiation service",
      "services/fraud-detection/ - Rule-based fraud engine",
      "services/settlement/ - Settlement processing",
      "shared/types/ - Shared DTOs and interfaces",
      "docker-compose.yml - Multi-service orchestration",
    ],
    difficulty: "advanced",
    instantRun: false,
    icon: "Landmark",
    gradient: "from-emerald-500 to-teal-600",
  },
  {
    id: 3,
    title: "Interactive REST API Playground",
    subtitle: "Single HTML File \u2014 Instant Run",
    description:
      "A sleek, self-contained API testing tool in a single HTML file. Features a beautiful UI for constructing HTTP requests, viewing formatted responses, managing request history, and saving collections.",
    techStack: ["HTML5", "CSS3", "Vanilla JavaScript", "Fetch API"],
    category: "html-instant",
    categoryLabel: "HTML Instant Run",
    features: [
      "GET, POST, PUT, PATCH, DELETE request builder",
      "JSON syntax highlighting with formatting",
      "Request history with local storage persistence",
      "Custom headers and auth token management",
      "Response time measurement and status codes",
      "Dark/light mode toggle",
    ],
    githubStructure: [
      "index.html - Complete self-contained application",
      "README.md - Usage guide and screenshots",
    ],
    difficulty: "beginner",
    instantRun: true,
    icon: "Globe",
    gradient: "from-blue-500 to-cyan-600",
  },
  {
    id: 4,
    title: "Microservices Health Monitor",
    subtitle: "Full-Stack Real-time Dashboard",
    description:
      "A real-time microservices monitoring dashboard that tracks health, latency, error rates, and resource utilization across distributed services. Features beautiful animated charts, alerting rules, and service dependency mapping.",
    techStack: ["React", "TypeScript", "Node.js", "WebSocket", "Recharts", "TailwindCSS"],
    category: "fullstack",
    categoryLabel: "Full-Stack",
    features: [
      "Real-time service health indicators",
      "Latency and throughput charts with historical data",
      "Service dependency topology map",
      "Configurable alerting thresholds",
      "Error rate tracking and anomaly detection",
      "Auto-refreshing dashboard with WebSocket",
    ],
    githubStructure: [
      "client/ - React dashboard with real-time charts",
      "server/ - Express API with WebSocket server",
      "mock-services/ - Simulated microservices",
      "README.md - Architecture and setup guide",
    ],
    difficulty: "intermediate",
    instantRun: false,
    icon: "Activity",
    gradient: "from-orange-500 to-red-500",
  },
  {
    id: 5,
    title: "GenAI Content Automation Pipeline",
    subtitle: "AI Workflow Orchestration",
    description:
      "An intelligent content generation pipeline that orchestrates multiple AI agents to research topics, generate drafts, edit content, and publish \u2014 all through a visual workflow builder.",
    techStack: ["React", "TypeScript", "Node.js", "OpenAI API", "LangChain", "TailwindCSS"],
    category: "ai-genai",
    categoryLabel: "AI / GenAI",
    features: [
      "Visual drag-and-drop workflow builder",
      "Multi-agent orchestration (researcher, writer, editor)",
      "Prompt template management system",
      "Content quality scoring and iteration",
      "Batch processing with progress tracking",
      "Export to Markdown, HTML, and PDF",
    ],
    githubStructure: [
      "client/ - React workflow builder UI",
      "server/ - Express orchestration engine",
      "agents/ - AI agent implementations",
      "templates/ - Prompt template library",
      "README.md - Architecture and AI patterns",
    ],
    difficulty: "advanced",
    instantRun: false,
    icon: "Sparkles",
    gradient: "from-pink-500 to-rose-600",
  },
  {
    id: 6,
    title: "Real-time Analytics Dashboard",
    subtitle: "Single HTML File \u2014 Instant Run",
    description:
      "A stunning real-time analytics dashboard in a single HTML file. Features animated charts, KPI cards, data tables, and interactive filters with mock data that simulates live updates.",
    techStack: ["HTML5", "CSS3", "JavaScript", "Chart.js", "CSS Animations"],
    category: "html-instant",
    categoryLabel: "HTML Instant Run",
    features: [
      "Animated KPI cards with trend indicators",
      "Multiple chart types (line, bar, doughnut, radar)",
      "Interactive data filtering and date ranges",
      "Responsive grid layout for any screen size",
      "Simulated real-time data updates",
      "Export dashboard as screenshot",
    ],
    githubStructure: [
      "index.html - Complete analytics dashboard",
      "README.md - Customization guide",
    ],
    difficulty: "beginner",
    instantRun: true,
    icon: "BarChart3",
    gradient: "from-indigo-500 to-blue-600",
  },
  {
    id: 7,
    title: "GitHub Copilot Workflow Bot",
    subtitle: "AI-Powered Developer Automation",
    description:
      "An intelligent GitHub bot that automates PR reviews, generates documentation, suggests test cases, and enforces coding standards using AI. Inspired by the winning project at the Danske Bank GitHub Copilot Hackathon.",
    techStack: ["Node.js", "TypeScript", "GitHub API", "OpenAI API", "Webhooks", "Express"],
    category: "ai-genai",
    categoryLabel: "AI / GenAI",
    features: [
      "Automated PR code review with AI suggestions",
      "Auto-generated documentation from code",
      "Test case generation for new functions",
      "Code style enforcement and linting",
      "Webhook-based event handling",
      "Configurable review rules and thresholds",
    ],
    githubStructure: [
      "src/ - Bot core logic and AI integration",
      "webhooks/ - GitHub webhook handlers",
      "templates/ - Review and doc templates",
      "config/ - Bot configuration and rules",
      "README.md - Setup and deployment guide",
    ],
    difficulty: "intermediate",
    instantRun: false,
    icon: "Bot",
    gradient: "from-amber-500 to-orange-600",
  },
  {
    id: 8,
    title: "Smart Error Monitoring System",
    subtitle: "Full-Stack Error Tracking Platform",
    description:
      "A production-grade error monitoring and alerting system. Captures, categorizes, and visualizes application errors with stack traces, user context, and frequency analysis.",
    techStack: ["React", "TypeScript", "Node.js", "Express", "PostgreSQL", "TailwindCSS"],
    category: "fullstack",
    categoryLabel: "Full-Stack",
    features: [
      "Intelligent error grouping and deduplication",
      "Stack trace visualization with source maps",
      "Error frequency trends and anomaly detection",
      "User impact analysis dashboard",
      "Email/webhook notification workflows",
      "SDK for easy integration into any app",
    ],
    githubStructure: [
      "dashboard/ - React error monitoring UI",
      "server/ - Express ingestion and API server",
      "sdk/ - JavaScript error capture SDK",
      "database/ - PostgreSQL schema and migrations",
      "README.md - Integration guide",
    ],
    difficulty: "advanced",
    instantRun: false,
    icon: "ShieldAlert",
    gradient: "from-red-500 to-pink-600",
  },
  {
    id: 9,
    title: "AI Chat Interface",
    subtitle: "Single HTML File \u2014 Instant Run",
    description:
      "A beautiful, production-quality AI chat interface in a single HTML file. Features streaming message animations, markdown rendering, code syntax highlighting, conversation management, and a modern glass-morphism design.",
    techStack: ["HTML5", "CSS3", "JavaScript", "Marked.js", "Highlight.js", "CSS Glass Effects"],
    category: "html-instant",
    categoryLabel: "HTML Instant Run",
    features: [
      "Streaming text animation with typewriter effect",
      "Markdown rendering with code highlighting",
      "Conversation management (new, delete, rename)",
      "Message reactions and copy functionality",
      "Responsive mobile-first design",
      "Glass-morphism UI with smooth transitions",
    ],
    githubStructure: [
      "index.html - Complete chat application",
      "README.md - Customization and API integration guide",
    ],
    difficulty: "beginner",
    instantRun: true,
    icon: "MessageSquare",
    gradient: "from-teal-500 to-emerald-600",
  },
  {
    id: 10,
    title: "CI/CD Pipeline Visualizer",
    subtitle: "Frontend React Application",
    description:
      "A visual pipeline builder and executor dashboard for CI/CD workflows. Drag and drop pipeline stages, configure jobs, view execution logs, and track deployment history.",
    techStack: ["React", "TypeScript", "Framer Motion", "TailwindCSS", "Zustand"],
    category: "frontend",
    categoryLabel: "Frontend",
    features: [
      "Drag-and-drop pipeline stage builder",
      "Real-time execution progress visualization",
      "Job configuration with environment variables",
      "Execution log streaming with ANSI colors",
      "Deployment history timeline",
      "Pipeline YAML export and import",
    ],
    githubStructure: [
      "src/components/ - React pipeline components",
      "src/store/ - Zustand state management",
      "src/utils/ - Pipeline parsing and execution",
      "src/types/ - TypeScript interfaces",
      "README.md - Architecture and patterns guide",
    ],
    difficulty: "intermediate",
    instantRun: false,
    icon: "GitBranch",
    gradient: "from-cyan-500 to-blue-600",
  },
  {
    id: 11,
    title: "Enterprise Document Intelligence Platform",
    subtitle: "Full-Stack RAG + Vector Search + AI",
    description:
      "A production-grade document intelligence platform using Retrieval-Augmented Generation (RAG) to ingest, parse, and semantically search enterprise documents. Features PDF/DOCX ingestion, vector embeddings, conversational Q&A over documents, citation tracking, and role-based access control. Built for enterprise compliance and knowledge management at scale.",
    techStack: ["React", "TypeScript", "Node.js", "Express", "OpenAI API", "Pinecone", "PostgreSQL", "LangChain", "TailwindCSS"],
    category: "fullstack",
    categoryLabel: "Full-Stack",
    features: [
      "PDF/DOCX document ingestion with chunking pipeline",
      "Vector embedding generation and semantic search via Pinecone",
      "Conversational RAG Q&A with citation references",
      "Document version control and audit trail",
      "Role-based access control (RBAC) with team workspaces",
      "Real-time ingestion progress with WebSocket",
      "Export answers with source citations to PDF",
    ],
    githubStructure: [
      "src/client/ - React dashboard with document viewer",
      "src/server/ - Express API with RAG orchestration",
      "src/server/services/ - Embedding, search, and LLM services",
      "src/server/middleware/ - Auth, RBAC, and rate limiting",
      "src/shared/ - Shared types, schemas, and DTOs",
      "database/ - PostgreSQL migrations and seed data",
      "README.md - Architecture, RAG patterns, and deployment guide",
    ],
    difficulty: "advanced",
    instantRun: false,
    icon: "FileSearch",
    gradient: "from-violet-600 to-indigo-700",
  },
  {
    id: 12,
    title: "Real-Time Fraud Detection & AML Engine",
    subtitle: "Backend Event-Driven Microservices + ML",
    description:
      "A high-throughput, event-driven fraud detection and Anti-Money Laundering (AML) system designed for banking and fintech. Processes transaction streams in real-time, applies ML-based anomaly scoring, rule-based pattern matching, and generates Suspicious Activity Reports (SARs). Features regulatory compliance dashboards, case management, and audit-ready logging.",
    techStack: ["Node.js", "TypeScript", "Kafka", "Redis", "PostgreSQL", "TensorFlow.js", "Express", "Docker"],
    category: "backend",
    categoryLabel: "Backend",
    features: [
      "Real-time transaction stream processing with Kafka",
      "ML-based anomaly detection scoring engine",
      "Configurable rule engine for fraud pattern matching",
      "Suspicious Activity Report (SAR) auto-generation",
      "Case management workflow for investigators",
      "Graph analysis for money laundering network detection",
      "Regulatory compliance audit trail and reporting",
      "Circuit breaker and retry patterns for resilience",
    ],
    githubStructure: [
      "services/ingestion/ - Transaction stream consumer",
      "services/scoring-engine/ - ML anomaly scoring",
      "services/rule-engine/ - Configurable fraud rules",
      "services/case-management/ - Investigation workflows",
      "services/reporting/ - SAR and compliance reports",
      "shared/types/ - Shared DTOs and event schemas",
      "docker-compose.yml - Full stack orchestration",
      "README.md - Architecture, ML model details, and compliance",
    ],
    difficulty: "advanced",
    instantRun: false,
    icon: "Shield",
    gradient: "from-red-600 to-rose-700",
  },
  {
    id: 13,
    title: "AI-Powered API Gateway & Traffic Analyzer",
    subtitle: "Backend Infrastructure + AI Ops",
    description:
      "An intelligent API gateway that uses AI to dynamically manage rate limiting, detect anomalous traffic patterns, auto-generate API documentation, and provide predictive scaling recommendations. Features real-time traffic visualization, per-tenant quotas, circuit breakers, and AI-driven root cause analysis for API failures.",
    techStack: ["Node.js", "TypeScript", "Express", "Redis", "OpenAI API", "Prometheus", "Grafana", "Docker"],
    category: "backend",
    categoryLabel: "Backend",
    features: [
      "Dynamic AI-powered rate limiting and throttling",
      "Real-time traffic pattern anomaly detection",
      "Auto-generated OpenAPI documentation from traffic",
      "Predictive auto-scaling recommendations",
      "Per-tenant quota management and billing metering",
      "Circuit breaker with intelligent retry policies",
      "AI root cause analysis for 5xx error spikes",
      "Prometheus metrics and Grafana dashboards",
    ],
    githubStructure: [
      "src/gateway/ - Core proxy and routing engine",
      "src/ai/ - Anomaly detection and RCA services",
      "src/middleware/ - Rate limiter, auth, circuit breaker",
      "src/monitoring/ - Prometheus exporters and health checks",
      "src/admin/ - Tenant management and quota APIs",
      "config/ - Gateway rules and AI model configs",
      "docker-compose.yml - Gateway + Redis + Prometheus stack",
      "README.md - Architecture, AI patterns, and deployment",
    ],
    difficulty: "advanced",
    instantRun: false,
    icon: "Network",
    gradient: "from-sky-600 to-blue-700",
  },
  {
    id: 14,
    title: "Telecom Network Intelligence Dashboard",
    subtitle: "Full-Stack Real-Time Analytics + AI Predictions",
    description:
      "A production-grade telecom network monitoring and intelligence platform. Visualizes real-time network KPIs (latency, throughput, packet loss, jitter), uses AI to predict network congestion and failures, and provides automated incident correlation. Built for telecom NOC teams with SLA tracking, capacity planning, and AI-driven optimization recommendations.",
    techStack: ["React", "TypeScript", "Node.js", "WebSocket", "TensorFlow.js", "D3.js", "PostgreSQL", "Redis", "TailwindCSS"],
    category: "fullstack",
    categoryLabel: "Full-Stack",
    features: [
      "Real-time network topology visualization with D3.js",
      "AI-powered congestion prediction (30-min forecast)",
      "Automated incident correlation and root cause analysis",
      "SLA compliance tracking with breach alerts",
      "Capacity planning with trend analysis and forecasting",
      "Cell tower performance heatmaps",
      "Automated remediation runbook suggestions",
      "NOC team collaboration with incident chat",
    ],
    githubStructure: [
      "client/ - React dashboard with D3.js visualizations",
      "server/ - Express API with WebSocket streaming",
      "server/ai/ - Prediction models and anomaly detection",
      "server/services/ - Network data aggregation and alerting",
      "database/ - PostgreSQL time-series schemas",
      "simulators/ - Network traffic and failure simulators",
      "README.md - Telecom architecture and AI model guide",
    ],
    difficulty: "advanced",
    instantRun: false,
    icon: "Radio",
    gradient: "from-emerald-600 to-green-700",
  },
  {
    id: 15,
    title: "AI Code Migration & Modernization Assistant",
    subtitle: "Full-Stack AI Dev Tool + AST Analysis",
    description:
      "An AI-powered code migration assistant that analyzes legacy codebases and generates migration plans, refactored code, and test suites for modernization. Supports monolith-to-microservices decomposition, framework upgrades (e.g., Java 8 to 21, Angular to React), and dependency vulnerability remediation. Features AST-based analysis, AI-generated migration PRs, and progress tracking dashboards.",
    techStack: ["React", "TypeScript", "Node.js", "OpenAI API", "Tree-sitter", "PostgreSQL", "GitHub API", "TailwindCSS"],
    category: "ai-genai",
    categoryLabel: "AI / GenAI",
    features: [
      "AST-based codebase analysis with dependency graphing",
      "AI-generated migration plans with risk scoring",
      "Automated code transformation and refactoring",
      "Monolith decomposition with bounded context detection",
      "Test suite generation for migrated components",
      "GitHub PR auto-creation with diff preview",
      "Migration progress dashboard with burndown charts",
      "Vulnerability detection and remediation suggestions",
    ],
    githubStructure: [
      "client/ - React migration dashboard",
      "server/ - Express orchestration API",
      "server/analyzers/ - AST parsers and dependency graphing",
      "server/ai/ - LLM-powered migration and code generation",
      "server/github/ - GitHub API integration for PR creation",
      "shared/ - Shared types and migration schemas",
      "README.md - Architecture, AI patterns, and supported migrations",
    ],
    difficulty: "advanced",
    instantRun: false,
    icon: "Workflow",
    gradient: "from-amber-600 to-yellow-600",
  },
];
